feat: update

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -1,4 +1,4 @@
-name: CI/CD-Dev
+name: CI/CD--Dev
 
 on:
   pull_request:
@@ -7,6 +7,7 @@ on:
   push:
     branches:
       - dev
+
 env:
   DB_USERNAME: ${{ secrets.DB_USERNAME }}
   DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
@@ -67,76 +68,150 @@ jobs:
               kill $APP_PID
               exit 1
           fi
-
           kill $APP_PID
           echo "Application terminated Successfully."
-
       - name: Revert Migrations
         run: npm run migration:revert
         if: always()
+# name: CI/CD-Dev
 
-      # - name: Run tests
-      #   run: npm run test
+# on:
+#   pull_request:
+#     branches:
+#       - dev
+#   push:
+#     branches:
+#       - dev
+# env:
+#   DB_USERNAME: ${{ secrets.DB_USERNAME }}
+#   DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+#   DB_DATABASE: ${{ secrets.DB_DATABASE }}
+#   DB_HOST: ${{ secrets.DB_HOST }}
+#   DB_PORT: ${{ secrets.DB_PORT }}
+#   DB_ENTITIES: ${{ secrets.DB_ENTITIES }}
+#   DB_MIGRATIONS: ${{ secrets.DB_MIGRATIONS }}
+#   DB_TYPE: 'postgres'
+#   PROFILE: 'staging'
+#   NODE_ENV: 'development'
+#   PORT: 3000
 
-      # - name: Generate migrations
-      #   run: npm run migration:generate
+# jobs:
+#   test-and-build-dev:
+#     runs-on: ubuntu-latest
+#     if: github.event_name == 'pull_request'
 
-      # - name: Run migrations
-      #   run: npm run migration:run
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
 
-      # - name: Start application
-      #   run: npm run start:prod
+#       - name: Set up Node.js
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: '18'
 
-      # - name: Check application logs and exit status
-      #   run: |
-      #     kill -0 $(cat app.pid) 2>/dev/null
-      #     if [ $? -eq 0 ]; then
-      #       echo "Application is running successfully."
-      #     else
-      #       echo "Application failed to start."
-      #       cat app.log
-      #       exit 1
-      #     fi
+#       - name: Install dependencies
+#         run: npm install --include=dev
 
-      # - name: Stop the application
-      #   run: kill $(jobs -p)
-      #   if: always()
+#       - name: Build project
+#         run: npm run build
 
-      # - name: Start application
-      #   run: npm run migration:revert
-      #   if: always()
+#       - name: Run tests
+#         run: npm run test
 
-  # deploy-push:
-  #   runs-on: ubuntu-latest
-  #   if: github.event_name == 'push'
+#       - name: Generate migrations
+#         run: npm run migration:generate
 
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v3
+#       - name: Run migrations
+#         run: npm run migration:run
 
-  #     - name: Set up Node.js
-  #       uses: actions/setup-node@v3
-  #       with:
-  #         node-version: '18'
+#       - name: Start application
+#         run: |
+#           npm run start:prod > app.log 2>&1 &
+#           APP_PID=$!
+#           echo $APP_PID
+#           echo "Application started with PID $APP_PID"
+#           sleep 30 # Wait for the application to start
+#           tail -f app.log &
+#           # Check application status with curl
+#           if curl --retry 5 --retry-delay 5 --max-time 10 http://localhost:3000/health; then
+#               echo "Application is up and running."
+#           else
+#               echo "Application failed to start. Logs:"
+#               cat app.log
+#               echo "Exiting workflow due to application failure."
+#               kill $APP_PID
+#               exit 1
+#           fi
 
-  #     - name: Install dependencies
-  #       run: npm install --include=dev
+#           kill $APP_PID
+#           echo "Application terminated Successfully."
 
-  #     - name: Build project
-  #       run: npm run build
+#       - name: Revert Migrations
+#         run: npm run migration:revert
+#         if: always()
 
-  #     - name: Run tests
-  #       run: npm run test
+#       # - name: Run tests
+#       #   run: npm run test
 
-  #     - name: Deploying to virtual machine
-  #       uses: appleboy/ssh-action@v1.0.3
-  #       with:
-  #         host: ${{ secrets.SERVER_HOST }}
-  #         username: ${{ secrets.SERVER_USER }}
-  #         # key: ${{ secrets.SERVER_PRIVATE_KEY }}
-  #         password: ${{ secrets.SERVER_PASSWORD }}
-  #         port: ${{ secrets.SERVER_PORT }}
-  #         script: |
-  #           echo "hello"
-  #           export PATH=$PATH:/home/teamalpha/.nvm/versions/node/v20.15.1/bin
-  #           bash ~/deployment.sh
+#       # - name: Generate migrations
+#       #   run: npm run migration:generate
+
+#       # - name: Run migrations
+#       #   run: npm run migration:run
+
+#       # - name: Start application
+#       #   run: npm run start:prod
+
+#       # - name: Check application logs and exit status
+#       #   run: |
+#       #     kill -0 $(cat app.pid) 2>/dev/null
+#       #     if [ $? -eq 0 ]; then
+#       #       echo "Application is running successfully."
+#       #     else
+#       #       echo "Application failed to start."
+#       #       cat app.log
+#       #       exit 1
+#       #     fi
+
+#       # - name: Stop the application
+#       #   run: kill $(jobs -p)
+#       #   if: always()
+
+#       # - name: Start application
+#       #   run: npm run migration:revert
+#       #   if: always()
+
+#   # deploy-push:
+#   #   runs-on: ubuntu-latest
+#   #   if: github.event_name == 'push'
+
+#   #   steps:
+#   #     - name: Checkout code
+#   #       uses: actions/checkout@v3
+
+#   #     - name: Set up Node.js
+#   #       uses: actions/setup-node@v3
+#   #       with:
+#   #         node-version: '18'
+
+#   #     - name: Install dependencies
+#   #       run: npm install --include=dev
+
+#   #     - name: Build project
+#   #       run: npm run build
+
+#   #     - name: Run tests
+#   #       run: npm run test
+
+#   #     - name: Deploying to virtual machine
+#   #       uses: appleboy/ssh-action@v1.0.3
+#   #       with:
+#   #         host: ${{ secrets.SERVER_HOST }}
+#   #         username: ${{ secrets.SERVER_USER }}
+#   #         # key: ${{ secrets.SERVER_PRIVATE_KEY }}
+#   #         password: ${{ secrets.SERVER_PASSWORD }}
+#   #         port: ${{ secrets.SERVER_PORT }}
+#   #         script: |
+#   #           echo "hello"
+#   #           export PATH=$PATH:/home/teamalpha/.nvm/versions/node/v20.15.1/bin
+#   #           bash ~/deployment.sh
